version: '3'
services:
  streamlit:
    build: .
    expose:
      - "8501"
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - streamlit
